apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.spring.labels }}-deployment"
  labels:
    app: "{{ .Values.spring.labels }}"

spec:
  replicas: 2
  selector:
    matchLabels:
      app: "{{ .Values.spring.labels }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.spring.labels }}"
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: "{{ .Values.spring.labels }}"
          image: "{{ .Values.spring.image.repository }}:{{ .Values.spring.image.tag }}"
          ports:
            - containerPort: {{ .Values.spring.service.user.port }}
          resources:
            requests:
              cpu: "200m"
              memory: "400Mi"
            limits:
              cpu: "400m"
              memory: "800Mi"

          env:
            - name: DB_URL
              value: "{{ .Values.spring.datasource.url }}"
            - name: DB_USERNAME
              value: "{{ .Values.spring.datasource.username }}"
            - name: DB_PASSWORD
              value: "{{ .Values.spring.datasource.password }}"

          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.spring.service.user.port }}
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 3
            successThreshold: 1

          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.spring.service.user.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
