{{- if .Values.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.spring.labels }}-hpa
  labels:
    app: {{ .Values.spring.labels }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.spring.labels }}-deployment

  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}

  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.scaleUp.stabilizationWindowSeconds }}
      policies:
        - type: {{ .Values.autoscaling.behavior.scaleUp.policies[0].type }}
          value: {{ .Values.autoscaling.behavior.scaleUp.policies[0].value }}
          periodSeconds: {{ .Values.autoscaling.behavior.scaleUp.policies[0].periodSeconds }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.scaleDown.stabilizationWindowSeconds }}
      policies:
        - type: {{ .Values.autoscaling.behavior.scaleDown.policies[0].type }}
          value: {{ .Values.autoscaling.behavior.scaleDown.policies[0].value }}
          periodSeconds: {{ .Values.autoscaling.behavior.scaleDown.policies[0].periodSeconds }} {{- end }}
